[output]
label=V 
command=~/.config/i3/getDefaultSink.sh
signal=10
interval=once

[battery]
#label=BAT
command=~/.config/i3/battery.sh
#label=⚡
instance=0
interval=30 

[brightness]
#label=BAT
command=~/.config/i3/getBrightness.sh
#label=⚡
instance=0
interval=30 

# Update time every 5 seconds
[time]
command=date +"%A %m/%d %H:%M"
interval=1
